### PR TITLE
Modified endpoint variable to use full window.location.href.

### PR DESCRIPTION
**Pull request by nathanKramer**
Seems to solve edge cases like auth and package installs (Not 100% sure on implications and only tested a few times, maybe try it out locally before accepting)

### CODE REVIEW

**Comment by lukemcfarlane** [comment]
Any thoughts @Oblongmana????

**Comment by Oblongmana** [comment]
Tested, works well, makes sense. Nice one @nathanKramer :+1: 

Merge pls @lukemcfarlane (I thought I could merge, but I can't)

**Comment by Oblongmana** [comment]
One small thing to note though @nathanKramer - recommend following these guidelines for your commit messages: http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html

Basically - 50 chars max in the 1st line, two newlines, then anything wordy you have to write (wrapped to 72 chars).

**Comment by nathanKramer** [comment]
Ah, ok.
Thanks for the info @Oblongmana

**Pull request merged**
